/** @format */

export enum FavoriteCitiesTypes {
  ADD_FAVORITE_CITY = "ADD_FAVORITE_CITY",
  DELETE_FAVORITE_CITY = "DELETE_FAVORITE_CITY",
  SET_FAVORITE_ICON_ACTIVE = "SET_FAVORITE_ICON_ACTIVE",
}
