/** @format */

export enum WeatherTypes {
  CURRENT_WEATHER = "CURRENT_WEATHER",
  CURRENT_WEATHER_ERROR = "CURRENT_WEATHER_ERROR",
  SET_CITY = "SET_CITY",
  SET_UNIT_CONVERSION = "SET_UNIT_CONVERSION",
  FIVE_DAYS_FORECAST = "FIVE_DAYS_FORECAST",
  FIVE_DAYS_FORECAST_ERROR = "FIVE_DAYS_FORECAST_ERROR",
}
