/** @format */

export enum WeatherTypes {
  CURRENT_WEATHER = "CURRENT_WEATHER",
  CURRENT_WEATHER_ERROR = "CURRENT_WEATHER_ERROR",
  SET_CITY_KEY = "SET_CITY_KEY",
  SET_METRIC_CONVERSION = "SET_METRIC_CONVERSION",
  SET_WEATHER = "SET_WEATHER",
  SET_FAVORITE_ICON_ACTIVE = "SET_FAVORITE_ICON_ACTIVE",
  FIVE_DAYS_FORECAST = "FIVE_DAYS_FORECAST",
  FIVE_DAYS_FORECAST_ERROR = "FIVE_DAY_FORECAST_ERROR",
}
