/** @format */

export enum WeatherTypes {
  CURRENT_WEATHER = "CURRENT_WEATHER",
  SET_CITY = "SET_CITY",
  SET_UNIT_CONVERSION = "SET_UNIT_CONVERSION",
  FIVE_DAYS_FORECAST = "FIVE_DAYS_FORECAST",
}
