/** @format */

export enum WeatherTypes {
  CURRENT_WEATHER = "CURRENT_WEATHER",
  CURRENT_WEATHER_ERROR = "CURRENT_WEATHER_ERROR",
  SET_CITY_KEY = "SET_CITY_KEY",
  SET_METRIC_CONVERSION = "SET_METRIC_CONVERSION",
  SET_WEATHER = "SET_WEATHER",
  // FIVE_DAY_FORECAST = "FIVE_DAY_FORECAST",
}
